# Permalinks
permalink:        pretty

# Setup
url:              ''

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            慕有枝

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  [myz]() >
  关注前端...
  [immyz.com]()

# The tags listed as entries in the sidebar
sidebar_tags:     [js,vue,nodejs,git]

# Fallback image and color if not overwritten for tag or post
image:            /public/img/nap.jpg
color:            '#A85641'

author:
  name:           'Florian Klampfer'

  # Setting social media usernames will add icons at the bottom of the sidebar
  twitter:        '603451688'
  github:         'durling'
  weibo:          '603451688'

  # Setting a disqus username will enable the comment section
  # disqus:         ''

  # This photo will be used in the about section
  photo:          /public/img/luanshu.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    山有木兮
    在河之洲
    取次花丛
    谓我何求

  #Read my thoughts on [#software](http://qwtel.com/tag/software) and [#cryptoeconomics](http://qwtel.com/tag/cryptoeconomics).

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
