# Permalinks
permalink:        pretty

# Setup
url:              ''

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            nuoluan_blog

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  曾经小僧 >
  web前端一枚...
  [cengseng.com](http://weibo.com/603451688){:target="_blank"}

# The tags listed as entries in the sidebar
sidebar_tags:     [jekyll,hyde,nodejs,git]

# Fallback image and color if not overwritten for tag or post
image:            /public/img/nap.jpg
color:            '#A85641'

author:
  name:           'Florian Klampfer'

  # Setting social media usernames will add icons at the bottom of the sidebar
  twitter:        '603451688'
  github:         durling
  weibo:          '603451688'

  # Setting a disqus username will enable the comment section
  disqus:         durling

  # This photo will be used in the about section
  photo:          /public/img/cengseng.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    山有木兮木有枝
    曾经小僧难化猿

    #Read my thoughts on [#software](http://qwtel.com/tag/software) and [#cryptoeconomics](http://qwtel.com/tag/cryptoeconomics).

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
