# Permalinks
permalink:        pretty

# Setup
url:              ''

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            心刀 の 博客

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  [Xindot.com]()

# The tags listed as entries in the sidebar
sidebar_tags:     [js,react,vue,nodejs,git,css]

# Fallback image and color if not overwritten for tag or post
image:            http://img.6h5.cn/xindot-blog/bg-0002-s.jpeg
color:            '#A85641'

author:
  name:           心刀

  # Setting social media usernames will add icons at the bottom of the sidebar
  # twitter:        ''
  github:         Xindot
  weibo:          '603451688'
  zhihu:          Durling_Xie
  jianshu:        423b873cad24

  # Setting a disqus username will enable the comment section
  # disqus:         ''

  # This photo will be used in the about section
  photo:          http://img.6h5.cn/xindot-blog/Xindot-logo-1.png

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    **在**你身边
    **恰**到好处

  # Read my thoughts on [#software](http://qwtel.com/tag/software) and [#cryptoeconomics](http://qwtel.com/tag/cryptoeconomics).

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true

# 附加
attach:
  # 首页右上 图片链接
  index_right: 
    - ['Nginx 完全解读指南','https://s.imooc.com/WGiCHZk','慕课网']

  # 首页底部 图片链接
  index_bottom: 
    - ['Nginx 完全解读指南','https://s.imooc.com/WGiCHZk','慕课网']
  
  # 推荐课程
  courses: 
    - ['Git原理详解与实操指南','https://s.imooc.com/Wqtndwh','慕课网']
    - ['Nginx 完全解读指南','https://s.imooc.com/WGiCHZk','慕课网']
    - ['你不知道的前端性能优化技巧','https://s.imooc.com/WeRSmge','慕课网']
    - ['一条龙的 Node·Vue·React 服务器部署','https://s.imooc.com/WlRnl3v','慕课网']

  # 标签分类底部 图片链接
  tag_center: 
    - ['Nginx 完全解读指南','https://s.imooc.com/WGiCHZk','慕课网']

  # 我的书架
  books:
    - ['Vue js指南','https://union-click.jd.com/jdc?e=&p=AyIGZRtdHQoRAFEYWBwyFQZTG1MSBBcBXRhrUV1KWQorAlBHU0VeBUVNR0ZbSkdETlcNVQtHRVNSUVNLXANBRA1XB14DS10cQQVYD21XHgBUHVsdBRQCUxNYJQJIRR1jOlMHd3kJfSALZGABDUwualQeC2UaaxYDEABVG1gVByI3VRxrVGwSBlQcXBQLEzdUK1sRBBYOUR9fEwQaAFYrXBULItPJuo%2BAr8aR9cLhqzIiN1YrayUCIgRlWTUSARtSXRNaRVUSDlceXkALQQJcGVMWB0BUXRsIQgtHD2UZWhQGGw%3D%3D','https://img14.360buyimg.com/n1/jfs/t1/97355/29/1268/69177/5dbc45feE88616ce5/716f8a5a8b4b911c.jpg']
    - ['Vue js 前端开发 快速入门与专业应用','https://union-click.jd.com/jdc?e=&p=AyIGZRtdHQoRAFEYWBwyFQZTG1wUARUHUhxrUV1KWQorAlBHU0VeBUVNR0ZbSkdETlcNVQtHRVNSUVNLXANBRA1XB14DS10cQQVYD21XHgBUHVsSAxEAVRxcJXcWeSNuC15Rcg8BUhtzRm1%2FLUckEGIeC2UaaxYDEABVG1gVByI3VRxrVGwSBlQcXBQLEzdUK1sRBBYOUR1bEwYWAVUrXBULItPJuo%2BAr8aR9cLhqzIiN1YrayUCIgRlWTUSARtSXRNaRVUSDlceXkALQQJcGVMWB0BUXRsIQgtHD2UZWhQGGw%3D%3D','https://img14.360buyimg.com/n1/jfs/t1/47634/34/14936/19524/5dbc39e4E3cfdd88f/0e5d3e40e7d35dd3.jpg']
    - ['CSS世界','https://union-click.jd.com/jdc?e=&p=AyIGZRtcEQcaDlIZWBAyFgFcG1wRChQGXB1rUV1KWQorAlBHU0VeBUVNR0ZbSkdETlcNVQtHRVNSUVNLXANBRA1XB14DS10cQQVYD21XHgNTElsSBhoBVBJdJWBScyFCLkJQd3EBSDBRQ0ByS0YmHHIeC2UaaxYDEABVG1gVByI3VRxrVGwSBlQZWBwAFzdUK1sRBBYOUR1SEQMRBFIrXBULItPJuo%2BAr8aR9cLhqzIiN1YrayUCIgRlWTUQVRoBXRNeFgtCDgEeW0AAQgBRTFoTAUVXBhIIEAoXAGUZWhQGGw%3D%3D','https://img14.360buyimg.com/n1/jfs/t1/59796/26/11515/260164/5d8d8c41Eeffb8672/e19c8f55c288a3a4.jpg']
    - ['CSS选择器世界','https://union-click.jd.com/jdc?e=&p=AyIGZRtYFAcXBFIZWR0yEgRTG1gXBBM3EUQDS10iXhBeGlcJDBkNXg9JHU4YDk5ER1xOGRNLGEEcVV8BXURFUFdfC0RVU1JRUy1OVxUBFAdWGV0UMghHCk4eTXxvZCFhOnQLZ0JLeV1qZkQLWStaJQETBVIbWxYCFzdlG1wlUHzf462DsLMO0%2F%2BUjp2VIgZlG18TBhsDXBldFQQbBWUcWxwyxpv0z8641oSnjKHlJTIiBGUraxUyETcXdV4WCxYPVEkOEQdHBlAdWEIKFAcAEl5FAhEDVk5aQVITN1caWhEL','https://img14.360buyimg.com/n1/jfs/t1/56336/26/12823/78599/5d9be26dEb29260d7/a79533e4d99d0e88.jpg']
    - ['HTML 5&CSS完全手册第5版','https://union-click.jd.com/jdc?e=&p=AyIGZRtcEQcaDlIZWBAyFg9XHl0cARcFVRtrUV1KWQorAlBHU0VeBUVNR0ZbSkdETlcNVQtHRVNSUVNLXANBRA1XB14DS10cQQVYD21XHgNdGV4TCxECVxtbJUcSDxFZEBwAcgAVTTIVR2p6KGg7ZkQeC2UaaxYDEABVG1gVByI3VRxrVGwSBlQZWBwAFzdUK1sRBBYOURJSFAQbAlIrXBULItPJuo%2BAr8aR9cLhqzIiN1YrayUCIgRlWTUVBhYPUBILEgUbUFceUkZVQgVQEwxCBUEHUBleQldAVWUZWhQGGw%3D%3D','https://img14.360buyimg.com/n1/jfs/t1/103105/24/124/368235/5da7ec9fE43295072/01cd2f5ed3d2e5a2.jpg']
    - ['Node.js：来一打 C++ 扩展','https://union-click.jd.com/jdc?e=&p=AyIGZRlaEAQUBlMZWiUFEgVUE1wdChoGVCsfSlpMWGVCHlBDUAxLBQNQVk4YCQQAQB1AWQkFHUVBRhkSQw9THUJVEEMFSgxUVxZPI0AOFQdXGlMSChoPVBprdXtWXxMSWm9hQn0CUwxpX0FMNG8SQw4eN1QrWBQAFQdVGFsQMiIHUisaewobA1UbaxQyEgNTH1IRCxMPVhpaHDIVB1wrj4mjxpL4z82126i5ZStrFjIiN1UrWCVAfFUAHVtFVxFQXR8IFAcTAFVLDhRRElRWTAgRURcHUBJeJQATBlES','https://img14.360buyimg.com/n1/jfs/t22156/62/1031240436/82315/e8fcc009/5b1f68c4N088ccc9c.jpg']
    - ['狼书（卷1）：更了不起的Node.js','https://union-click.jd.com/jdc?e=&p=AyIGZRtYFAcXBFIZWR0yEgRSGFkWBxs3EUQDS10iXhBeGlcJDBkNXg9JHU4YDk5ER1xOGRNLGEEcVV8BXURFUFdfC0RVU1JRUy1OVxUBFQRXGF4cMlN4KngkXVlPYidtDldxQngxYT1PUUQLWStaJQETBVIbWxYCFzdlG1wlUHzf462DsLMO0%2F%2BUjp2VIgZlG18TBhsDXRpSHAsWBmUcWxwyxpv0z8641oSnjKHlJTIiBGUraxUyETcXdV8QCkIEURsIEFZABFBIDBRSFwNTEg5BBkEPVB9cFgFBN1caWhEL','https://img14.360buyimg.com/n1/jfs/t1/33065/2/12816/74008/5cf48481E3044abef/424de8af99b33ecc.jpg']
    - ['Node.js实战：使用Egg.js+Vue.js+Docker构建渐进式、可持续集成与交付应用','https://union-click.jd.com/jdc?e=&p=AyIGZRtYFAcXBFIZWR0yEgRQGF4SABo3EUQDS10iXhBeGlcJDBkNXg9JHU4YDk5ER1xOGRNLGEEcVV8BXURFUFdfC0RVU1JRUy1OVxUBFwRQHFkdMhFTNxILHFFbZz1bB2pWT1VdHFwSUFQLWStaJQETBVIbWxYCFzdlG1wlUHzf462DsLMO0%2F%2BUjp2VIgZlG18TBhsDXRtTEQIWBWUcWxwyxpv0z8641oSnjKHlJTIiBGUraxUyETcXdV8QCkIEURsIEFZABFBIDBRSFwNTEg5BBkEPVB9cFgFBN1caWhEL','https://img14.360buyimg.com/n1/jfs/t1/3851/39/13108/83531/5bd67769Ef70aa8b5/16c6591f79325c6f.jpg']
    - ['深入React技术栈','https://union-click.jd.com/jdc?e=&p=AyIGZRtYFAcXBFIZWR0yEgRUHFISABU3EUQDS10iXhBeGlcJDBkNXg9JHU4YDk5ER1xOGRNLGEEcVV8BXURFUFdfC0RVU1JRUy1OVxUBEwBcHFkSMlddE0EYEGpPZVBHIRR1QHEBcwcPZ3ILWStaJQETBVIbWxYCFzdlG1wlUHzf462DsLMO0%2F%2BUjp2VIgZlG18TBhsDXB9fEwIaAWUcWxwyxpv0z8641oSnjKHlJTIiBGUraxUyETcXdQgSB0cEURxYHQITUlAdXBELEwVUHVocBEdSBx4LHFBHN1caWhEL','https://img14.360buyimg.com/n1/jfs/t3640/142/1695345313/491175/474b0f11/582e6f62N531a0ddd.jpg']
    - ['技术之瞳 阿里巴巴技术笔试心得','https://union-click.jd.com/jdc?e=&p=AyIGZR1TFgsUBFYYXSUCEgdRE10SAhsDXCsfSlpMWGVCHlBDUAxLBQNQVk4YCQQAQB1AWQkFHUVBRhkSQw9THUJVEEMFSgxUVxZPI0AOEgdVH1MTBRIOURJrD1pPBlVHLkNhEwQecykSB3AdT0EuZQ4eN1QrWBQAFQdVGFsQMiIHUisaewYSA1UeaxQyEgNTH1IRCxQGUxpdFDIVB1wrj4mjxpL4z82126i5ZStrFjIiN1UrWCVAfFVRHg8RBxQCUBpaRgcSBVdIWxEFEFRUHA8cBkAFXRxTJQATBlES','https://img14.360buyimg.com/n1/jfs/t3226/275/4935527670/222522/969d6f86/5859edc0Na26f4857.jpg']

  # 友情链接 文字链接
  links:
    - ['张鑫旭','https://www.zhangxinxu.com/']
    - ['羡辙','http://zhangwenli.com/']
    - ['yuany','http://yuany.net/']
    - ['念然网络','https://www.nianran.net/']

