# Permalinks
permalink:        pretty

# Setup
url:              ''

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            点心 の 博客

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  [Xindot.com]()

# The tags listed as entries in the sidebar
sidebar_tags:     [js,react,vue,nodejs,git,css]

# Fallback image and color if not overwritten for tag or post
image:            http://img.6h5.cn/xindot-blog/bg-0002-s.jpeg
color:            '#A85641'

author:
  name:           点心

  # Setting social media usernames will add icons at the bottom of the sidebar
  # twitter:        ''
  github:         Xindot
  weibo:          '603451688'
  zhihu:          Durling_Xie
  jianshu:        423b873cad24

  # Setting a disqus username will enable the comment section
  # disqus:         ''

  # This photo will be used in the about section
  photo:          http://img.6h5.cn/xindot-blog/Xindot-logo-1.png

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    **在**你身边
    **恰**到好处

  #Read my thoughts on [#software](http://qwtel.com/tag/software) and [#cryptoeconomics](http://qwtel.com/tag/cryptoeconomics).

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
